# VirtualHost dla portu 80 (HTTP) - do przekierowywania na HTTPS
<VirtualHost *:80>
    ServerName localhost
    
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

# VirtualHost dla portu 443 (HTTPS)
<VirtualHost *:443>
    ServerName localhost
    DocumentRoot /var/www/html/

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/server.crt
    SSLCertificateKeyFile /etc/ssl/private/server.key

    ErrorLog ${APACHE_LOG_DIR}/error_ssl.log
    CustomLog ${APACHE_LOG_DIR}/access_ssl.log combined

    <Directory /var/www/html/>
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>